// Viber terrain chunk material — 8 simultaneous ground layers per chunk.
//
// Each terrain chunk carries its OWN material: the eight pool textures with
// the highest aggregate weight in that chunk + TWO RGBA8 splat planes baked
// per chunk (plane 0 = slots 0–3, plane 1 = slots 4–7; weights renormalized
// to sum 1 across both). Areas of the world can render completely different
// layer sets.
//
// WORLD SPECIALIZATION: `viber run` rewrites the CONFIG block below from the
// `<Terrain>` spec before the renderer loads this file.
//
// BINDINGS — the material is **bindless** (`TerrainChunkMaterial`), and it
// has to be: a non-bindless custom material with a single texture binding
// segfaults the NVIDIA driver inside `vkCreatePipelineLayout`. So the
// textures live in the shared arrays of `bevy_render::bindless` and this
// shader only carries INDICES into them, read from the index table at
// binding 0. The `#else` branch is the portable non-bindless layout (used
// on any device where bevy turns bindless off).

#import bevy_pbr::forward_io::{VertexOutput, FragmentOutput}
#import bevy_pbr::mesh_view_bindings::view
// Pipeline PBR REAL: `apply_pbr_lighting` traz o sol direcional (com as
// cascades de sombra — o chão passa a receber as sombras das árvores/props),
// as luzes pontuais clusterizadas (as lanternas acendem o terreno à noite),
// a luz ambiente e o specular; `main_pass_post_lighting_processing` aplica a
// fog da câmara (define DISTANCE_FOG do view key + bit FOG_ENABLED abaixo).
// NÃO importar `bevy_pbr::pbr_fragment`: puxa `pbr_bindings::material_indices`
// (StandardMaterial) que CONFLITUA com a nossa tabela bindless em
// group(#{MATERIAL_BIND_GROUP}).binding(0) — o PbrInput é construído à mão.
#import bevy_pbr::pbr_types::{pbr_input_new, STANDARD_MATERIAL_FLAGS_FOG_ENABLED_BIT}
#import bevy_pbr::pbr_functions::{apply_pbr_lighting, main_pass_post_lighting_processing, calculate_view}
#import bevy_pbr::lighting::perceptualRoughnessToRoughness
#import bevy_pbr::mesh_bindings::mesh

#ifdef BINDLESS
#import bevy_render::bindless::{bindless_textures_2d, bindless_samplers_filtering}
#endif  // BINDLESS

// SSAO — a textura e o define vêm do view key (componente na câmara); sem o
// componente o bloco some e a oclusão fica 1.0.
#ifdef SCREEN_SPACE_AMBIENT_OCCLUSION
#import bevy_pbr::mesh_view_bindings::screen_space_ambient_occlusion_texture
#import bevy_pbr::ssao_utils::ssao_multibounce
#endif

// === WORLD CONFIG (generated by `viber run` — edit the XML, not this block) ===
// HISTÓRICO: estes consts eram lidos pelo fragment; hoje os MESMOS valores
// entram no uniform (`TerrainChunkParams::walls_a`/`walls_b`, inicializados
// do XML pelo bootstrap) para `viber.debug.ground{...}` os mover AO VIVO.
// O bloco mantém-se por paridade com water/sky.
const CFG_TRI_SLOPE: f32 = 0.5;
const CFG_TRI_SOFT: f32 = 0.12;
const CFG_STRATA_SPACING: f32 = 4;
const CFG_STRATA_STRENGTH: f32 = 0.25;
const CFG_ROCK_DARKEN: f32 = 0.45;
const CFG_STREAK: f32 = 0.5;
const CFG_MOSS: f32 = 0.35;
// === END WORLD CONFIG ===

// Per-chunk layer table. `tiles[i].x` is the tile size in meters of layer i,
// `tints/flats/roughs` its color correction, flat far color and perceptual
// roughness; `chunk` places the planes: xy = origin XZ, z = edge size,
// w = index (0..7) of the rock layer for the triplanar walls, -1 = off.
// `day_tint.rgb` multiplies the final albedo (day/night cycle);
// `sun_dir.xyz` is the sun TRAVEL direction (where the light goes — the
// same sun the shadows follow, published with the day-tint steps).
struct TerrainChunkParams {
    tiles: array<vec4<f32>, 8>,
    tints: array<vec4<f32>, 8>,
    flats: array<vec4<f32>, 8>,
    roughs: array<vec4<f32>, 8>,
    chunk: vec4<f32>,
    day_tint: vec4<f32>,
    sun_dir: vec4<f32>,
    // Pele das paredes ao vivo (viber.debug.ground{...}):
    // walls_a = tri_slope, tri_soft, strata_spacing, strata_strength;
    // walls_b = rock_darken, streaks, moss, livre.
    walls_a: vec4<f32>,
    walls_b: vec4<f32>,
};

#ifdef BINDLESS

// Bindless index table — one entry per material slot; the field order is the
// bindless-index order declared by `TerrainChunkMaterial`
// (`#[data(0, …)]` then the thirty-four texture/sampler pairs at 1..68: eight
// albedos, two splat planes, eight normal maps, eight height maps, eight AO
// maps).
struct TerrainChunkBindings {
    material: u32,         // 0
    layer0_texture: u32,   // 1
    layer0_sampler: u32,   // 2
    layer1_texture: u32,   // 3
    layer1_sampler: u32,   // 4
    layer2_texture: u32,   // 5
    layer2_sampler: u32,   // 6
    layer3_texture: u32,   // 7
    layer3_sampler: u32,   // 8
    layer4_texture: u32,   // 9
    layer4_sampler: u32,   // 10
    layer5_texture: u32,   // 11
    layer5_sampler: u32,   // 12
    layer6_texture: u32,   // 13
    layer6_sampler: u32,   // 14
    layer7_texture: u32,   // 15
    layer7_sampler: u32,   // 16
    splat_texture: u32,    // 17
    splat_sampler: u32,    // 18
    splat2_texture: u32,   // 19
    splat2_sampler: u32,   // 20
    layer0_normal_texture: u32, // 21
    layer0_normal_sampler: u32, // 22
    layer1_normal_texture: u32, // 23
    layer1_normal_sampler: u32, // 24
    layer2_normal_texture: u32, // 25
    layer2_normal_sampler: u32, // 26
    layer3_normal_texture: u32, // 27
    layer3_normal_sampler: u32, // 28
    layer4_normal_texture: u32, // 29
    layer4_normal_sampler: u32, // 30
    layer5_normal_texture: u32, // 31
    layer5_normal_sampler: u32, // 32
    layer6_normal_texture: u32, // 33
    layer6_normal_sampler: u32, // 34
    layer7_normal_texture: u32, // 35
    layer7_normal_sampler: u32, // 36
    layer0_height_texture: u32, // 37
    layer0_height_sampler: u32, // 38
    layer1_height_texture: u32, // 39
    layer1_height_sampler: u32, // 40
    layer2_height_texture: u32, // 41
    layer2_height_sampler: u32, // 42
    layer3_height_texture: u32, // 43
    layer3_height_sampler: u32, // 44
    layer4_height_texture: u32, // 45
    layer4_height_sampler: u32, // 46
    layer5_height_texture: u32, // 47
    layer5_height_sampler: u32, // 48
    layer6_height_texture: u32, // 49
    layer6_height_sampler: u32, // 50
    layer7_height_texture: u32, // 51
    layer7_height_sampler: u32, // 52
    layer0_ao_texture: u32, // 53
    layer0_ao_sampler: u32, // 54
    layer1_ao_texture: u32, // 55
    layer1_ao_sampler: u32, // 56
    layer2_ao_texture: u32, // 57
    layer2_ao_sampler: u32, // 58
    layer3_ao_texture: u32, // 59
    layer3_ao_sampler: u32, // 60
    layer4_ao_texture: u32, // 61
    layer4_ao_sampler: u32, // 62
    layer5_ao_texture: u32, // 63
    layer5_ao_sampler: u32, // 64
    layer6_ao_texture: u32, // 65
    layer6_ao_sampler: u32, // 66
    layer7_ao_texture: u32, // 67
    layer7_ao_sampler: u32, // 68
}

@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<storage> material_indices: array<TerrainChunkBindings>;
@group(#{MATERIAL_BIND_GROUP}) @binding(10) var<storage> params_array: array<TerrainChunkParams>;

#else   // BINDLESS

@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<uniform> params_direct: TerrainChunkParams;
@group(#{MATERIAL_BIND_GROUP}) @binding(1) var layer0: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(2) var layer0_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(3) var layer1: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(4) var layer1_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(5) var layer2: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(6) var layer2_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(7) var layer3: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(8) var layer3_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(9) var layer4: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(10) var layer4_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(11) var layer5: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(12) var layer5_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(13) var layer6: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(14) var layer6_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(15) var layer7: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(16) var layer7_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(17) var splat: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(18) var splat_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(19) var splat2: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(20) var splat2_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(21) var layer0_normal: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(22) var layer0_normal_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(23) var layer1_normal: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(24) var layer1_normal_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(25) var layer2_normal: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(26) var layer2_normal_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(27) var layer3_normal: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(28) var layer3_normal_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(29) var layer4_normal: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(30) var layer4_normal_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(31) var layer5_normal: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(32) var layer5_normal_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(33) var layer6_normal: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(34) var layer6_normal_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(35) var layer7_normal: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(36) var layer7_normal_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(37) var layer0_height: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(38) var layer0_height_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(39) var layer1_height: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(40) var layer1_height_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(41) var layer2_height: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(42) var layer2_height_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(43) var layer3_height: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(44) var layer3_height_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(45) var layer4_height: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(46) var layer4_height_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(47) var layer5_height: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(48) var layer5_height_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(49) var layer6_height: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(50) var layer6_height_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(51) var layer7_height: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(52) var layer7_height_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(53) var layer0_ao: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(54) var layer0_ao_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(55) var layer1_ao: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(56) var layer1_ao_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(57) var layer2_ao: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(58) var layer2_ao_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(59) var layer3_ao: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(60) var layer3_ao_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(61) var layer4_ao: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(62) var layer4_ao_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(63) var layer5_ao: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(64) var layer5_ao_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(65) var layer6_ao: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(66) var layer6_ao_sampler: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(67) var layer7_ao: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(68) var layer7_ao_sampler: sampler;

#endif  // BINDLESS

// Achatamento por distância: perto vê-se o material, longe vê-se cor. FLAT_MIN
// é o achatamento mínimo colado à câmara — as fotos do pool têm contraste a
// mais para um mundo cel-ish mesmo aos pés do herói. r4 (2026-09-09): os
// limites esticaram (42/260 → 64/340) — o detalhe morria aos ~100 m e as
// encostas ao fundo liam-se como cor chapada; a aerial perspective
// (320–1100 m) assume o resto do caminho até ao horizonte.
const FLAT_NEAR: f32 = 64.0;
const FLAT_FAR: f32 = 340.0;
const FLAT_MIN: f32 = 0.15;

// Weights below this contribute nothing visible; skipping their texture
// fetch keeps the typical fragment at 2–3 layers instead of 4.
const WEIGHT_EPSILON: f32 = 0.004;

// Height-bias CONTÍNUO: cada layer ganha/perde peso proporcional à SUA
// altura (`h−0.5`), com teto/piso — a layer alta sai à frente na fronteira
// (a pedra sobre a relva) SEM colapso. A primeira versão redistribuía o
// PAR dominante com força 12: a layer perdedora colapsava a 0 e as
// fronteiras do splat — que são suaves — endureciam em LINHAS RETAS
// ("uma textura acaba, a outra começa", 2026-09-09). Multiplicativo com
// clamp é contínuo em todo o lado e mantém a largura da transição.
const HEIGHT_BIAS: f32 = 2.5;
/// Piso do multiplicador: a layer baixa nunca perde mais do que 65% do
/// peso — impossível desaparecer de golpe.
const HEIGHT_BIAS_MIN: f32 = 0.35;

// Força do AO do pool sobre o albedo (1 = total; 0.6 mantém o chão vivo).
const AO_STRENGTH: f32 = 0.6;

/// The chunk's table. `slot` is the material's index in the bindless slab
/// (always 0 without bindless).
fn chunk_params(slot: u32) -> TerrainChunkParams {
#ifdef BINDLESS
    return params_array[material_indices[slot].material];
#else   // BINDLESS
    return params_direct;
#endif  // BINDLESS
}

/// Layer `i` (0..7) of this chunk. Bindings cannot be indexed without
/// bindless, so the non-bindless path picks by explicit branches; the
/// gradients are always explicit, which is what makes the call legal from
/// the non-uniform per-weight branches below.
fn layer_sample(i: i32, slot: u32, uv: vec2<f32>, dx: vec2<f32>, dy: vec2<f32>) -> vec3<f32> {
#ifdef BINDLESS
    let idx = material_indices[slot];
    var tex = idx.layer0_texture;
    var samp = idx.layer0_sampler;
    if (i == 1) {
        tex = idx.layer1_texture;
        samp = idx.layer1_sampler;
    } else if (i == 2) {
        tex = idx.layer2_texture;
        samp = idx.layer2_sampler;
    } else if (i == 3) {
        tex = idx.layer3_texture;
        samp = idx.layer3_sampler;
    } else if (i == 4) {
        tex = idx.layer4_texture;
        samp = idx.layer4_sampler;
    } else if (i == 5) {
        tex = idx.layer5_texture;
        samp = idx.layer5_sampler;
    } else if (i == 6) {
        tex = idx.layer6_texture;
        samp = idx.layer6_sampler;
    } else if (i == 7) {
        tex = idx.layer7_texture;
        samp = idx.layer7_sampler;
    }
    return textureSampleGrad(
        bindless_textures_2d[tex],
        bindless_samplers_filtering[samp],
        uv,
        dx,
        dy,
    ).rgb;
#else   // BINDLESS
    if (i == 0) {
        return textureSampleGrad(layer0, layer0_sampler, uv, dx, dy).rgb;
    }
    if (i == 1) {
        return textureSampleGrad(layer1, layer1_sampler, uv, dx, dy).rgb;
    }
    if (i == 2) {
        return textureSampleGrad(layer2, layer2_sampler, uv, dx, dy).rgb;
    }
    if (i == 3) {
        return textureSampleGrad(layer3, layer3_sampler, uv, dx, dy).rgb;
    }
    if (i == 4) {
        return textureSampleGrad(layer4, layer4_sampler, uv, dx, dy).rgb;
    }
    if (i == 5) {
        return textureSampleGrad(layer5, layer5_sampler, uv, dx, dy).rgb;
    }
    if (i == 6) {
        return textureSampleGrad(layer6, layer6_sampler, uv, dx, dy).rgb;
    }
    return textureSampleGrad(layer7, layer7_sampler, uv, dx, dy).rgb;
#endif  // BINDLESS
}

/// Tangent-space normal map of layer `i` (0..7) — same selection/gradient
/// discipline as `layer_sample`. Devolve o RGB cru (0..1); o decode `*2−1`
/// é feito no chamador. Slots sem normal do pool carregam a imagem plana
/// (0.5, 0.5, 1) e contribuem com a normal geométrica.
fn layer_normal_sample(i: i32, slot: u32, uv: vec2<f32>, dx: vec2<f32>, dy: vec2<f32>) -> vec3<f32> {
#ifdef BINDLESS
    let idx = material_indices[slot];
    var tex = idx.layer0_normal_texture;
    var samp = idx.layer0_normal_sampler;
    if (i == 1) {
        tex = idx.layer1_normal_texture;
        samp = idx.layer1_normal_sampler;
    } else if (i == 2) {
        tex = idx.layer2_normal_texture;
        samp = idx.layer2_normal_sampler;
    } else if (i == 3) {
        tex = idx.layer3_normal_texture;
        samp = idx.layer3_normal_sampler;
    } else if (i == 4) {
        tex = idx.layer4_normal_texture;
        samp = idx.layer4_normal_sampler;
    } else if (i == 5) {
        tex = idx.layer5_normal_texture;
        samp = idx.layer5_normal_sampler;
    } else if (i == 6) {
        tex = idx.layer6_normal_texture;
        samp = idx.layer6_normal_sampler;
    } else if (i == 7) {
        tex = idx.layer7_normal_texture;
        samp = idx.layer7_normal_sampler;
    }
    return textureSampleGrad(
        bindless_textures_2d[tex],
        bindless_samplers_filtering[samp],
        uv,
        dx,
        dy,
    ).rgb;
#else   // BINDLESS
    if (i == 0) {
        return textureSampleGrad(layer0_normal, layer0_normal_sampler, uv, dx, dy).rgb;
    }
    if (i == 1) {
        return textureSampleGrad(layer1_normal, layer1_normal_sampler, uv, dx, dy).rgb;
    }
    if (i == 2) {
        return textureSampleGrad(layer2_normal, layer2_normal_sampler, uv, dx, dy).rgb;
    }
    if (i == 3) {
        return textureSampleGrad(layer3_normal, layer3_normal_sampler, uv, dx, dy).rgb;
    }
    if (i == 4) {
        return textureSampleGrad(layer4_normal, layer4_normal_sampler, uv, dx, dy).rgb;
    }
    if (i == 5) {
        return textureSampleGrad(layer5_normal, layer5_normal_sampler, uv, dx, dy).rgb;
    }
    if (i == 6) {
        return textureSampleGrad(layer6_normal, layer6_normal_sampler, uv, dx, dy).rgb;
    }
    return textureSampleGrad(layer7_normal, layer7_normal_sampler, uv, dx, dy).rgb;
#endif  // BINDLESS
}

/// Scalar map (height or AO) of layer `i` (0..7) — one selection chain for
/// both families (`height` = true → `height.ktx2`, false → `ao.ktx2`),
/// same gradient discipline as `layer_sample`. Planos (0.5 / 1.0) quando o
/// slot não tem o ficheiro: o height-blend devolve os pesos originais e o
/// AO devolve 1.0.
fn layer_scalar_sample(i: i32, slot: u32, uv: vec2<f32>, dx: vec2<f32>, dy: vec2<f32>, height: bool) -> f32 {
    let h = height;
#ifdef BINDLESS
    let idx = material_indices[slot];
    var tex = select(idx.layer0_height_texture, idx.layer0_ao_texture, !h);
    var samp = select(idx.layer0_height_sampler, idx.layer0_ao_sampler, !h);
    if (i == 1) {
        tex = select(idx.layer1_height_texture, idx.layer1_ao_texture, !h);
        samp = select(idx.layer1_height_sampler, idx.layer1_ao_sampler, !h);
    } else if (i == 2) {
        tex = select(idx.layer2_height_texture, idx.layer2_ao_texture, !h);
        samp = select(idx.layer2_height_sampler, idx.layer2_ao_sampler, !h);
    } else if (i == 3) {
        tex = select(idx.layer3_height_texture, idx.layer3_ao_texture, !h);
        samp = select(idx.layer3_height_sampler, idx.layer3_ao_sampler, !h);
    } else if (i == 4) {
        tex = select(idx.layer4_height_texture, idx.layer4_ao_texture, !h);
        samp = select(idx.layer4_height_sampler, idx.layer4_ao_sampler, !h);
    } else if (i == 5) {
        tex = select(idx.layer5_height_texture, idx.layer5_ao_texture, !h);
        samp = select(idx.layer5_height_sampler, idx.layer5_ao_sampler, !h);
    } else if (i == 6) {
        tex = select(idx.layer6_height_texture, idx.layer6_ao_texture, !h);
        samp = select(idx.layer6_height_sampler, idx.layer6_ao_sampler, !h);
    } else if (i == 7) {
        tex = select(idx.layer7_height_texture, idx.layer7_ao_texture, !h);
        samp = select(idx.layer7_height_sampler, idx.layer7_ao_sampler, !h);
    }
    return textureSampleGrad(
        bindless_textures_2d[tex],
        bindless_samplers_filtering[samp],
        uv,
        dx,
        dy,
    ).r;
#else   // BINDLESS
    // Cada ramo devolve DIRECTAMENTE: o naga exige que o argumento de
    // textura do textureSampleGrad seja um GLOBAL (uma local `var tex`
    // selecionada por if/else é rejeitada na validação).
    if (i == 0) {
        if (h) {
            return textureSampleGrad(layer0_height, layer0_height_sampler, uv, dx, dy).r;
        }
        return textureSampleGrad(layer0_ao, layer0_ao_sampler, uv, dx, dy).r;
    }
    if (i == 1) {
        if (h) {
            return textureSampleGrad(layer1_height, layer1_height_sampler, uv, dx, dy).r;
        }
        return textureSampleGrad(layer1_ao, layer1_ao_sampler, uv, dx, dy).r;
    }
    if (i == 2) {
        if (h) {
            return textureSampleGrad(layer2_height, layer2_height_sampler, uv, dx, dy).r;
        }
        return textureSampleGrad(layer2_ao, layer2_ao_sampler, uv, dx, dy).r;
    }
    if (i == 3) {
        if (h) {
            return textureSampleGrad(layer3_height, layer3_height_sampler, uv, dx, dy).r;
        }
        return textureSampleGrad(layer3_ao, layer3_ao_sampler, uv, dx, dy).r;
    }
    if (i == 4) {
        if (h) {
            return textureSampleGrad(layer4_height, layer4_height_sampler, uv, dx, dy).r;
        }
        return textureSampleGrad(layer4_ao, layer4_ao_sampler, uv, dx, dy).r;
    }
    if (i == 5) {
        if (h) {
            return textureSampleGrad(layer5_height, layer5_height_sampler, uv, dx, dy).r;
        }
        return textureSampleGrad(layer5_ao, layer5_ao_sampler, uv, dx, dy).r;
    }
    if (i == 6) {
        if (h) {
            return textureSampleGrad(layer6_height, layer6_height_sampler, uv, dx, dy).r;
        }
        return textureSampleGrad(layer6_ao, layer6_ao_sampler, uv, dx, dy).r;
    }
    if (h) {
        return textureSampleGrad(layer7_height, layer7_height_sampler, uv, dx, dy).r;
    }
    return textureSampleGrad(layer7_ao, layer7_ao_sampler, uv, dx, dy).r;
#endif  // BINDLESS
}

/// The chunk's splat planes (local 0..1 UVs over the chunk); plane 1 weights
/// slots 4–7.
fn splat_sample(slot: u32, uv: vec2<f32>, dx: vec2<f32>, dy: vec2<f32>) -> vec4<f32> {
#ifdef BINDLESS
    let idx = material_indices[slot];
    return textureSampleGrad(
        bindless_textures_2d[idx.splat_texture],
        bindless_samplers_filtering[idx.splat_sampler],
        uv,
        dx,
        dy,
    );
#else   // BINDLESS
    return textureSampleGrad(splat, splat_sampler, uv, dx, dy);
#endif  // BINDLESS
}

fn splat2_sample(slot: u32, uv: vec2<f32>, dx: vec2<f32>, dy: vec2<f32>) -> vec4<f32> {
#ifdef BINDLESS
    let idx = material_indices[slot];
    return textureSampleGrad(
        bindless_textures_2d[idx.splat2_texture],
        bindless_samplers_filtering[idx.splat2_sampler],
        uv,
        dx,
        dy,
    );
#else   // BINDLESS
    return textureSampleGrad(splat2, splat2_sampler, uv, dx, dy);
#endif  // BINDLESS
}

// ── Wall skin (deterministic hash noise — the rock detail needs no extra
// textures or bindings). Value noise in 2 octaves drives the runoff
// streaks and the moss patches.
fn hash21(p: vec2<f32>) -> f32 {
    return fract(sin(dot(p, vec2<f32>(127.1, 311.7))) * 43758.5453);
}
fn vnoise(p: vec2<f32>) -> f32 {
    let i = floor(p);
    let f = fract(p);
    let u = f * f * (3.0 - 2.0 * f);
    let a = mix(hash21(i), hash21(i + vec2<f32>(1.0, 0.0)), u.x);
    let b = mix(hash21(i + vec2<f32>(0.0, 1.0)), hash21(i + vec2<f32>(1.0, 1.0)), u.x);
    return mix(a, b, u.y);
}

@fragment
fn fragment(
    in: VertexOutput,
    @builtin(front_facing) is_front: bool,
) -> FragmentOutput {
#ifdef BINDLESS
    let slot = mesh[in.instance_index].material_and_lightmap_bind_group_slot & 0xffffu;
#else   // BINDLESS
    let slot = 0u;
#endif  // BINDLESS
    let params = chunk_params(slot);

    let world = in.world_position.xyz;
    let normal = select(-in.world_normal, in.world_normal, is_front);

    // Splat coverage of THIS chunk: local 0..1 UVs over the chunk plane. The
    // gradients are taken ONCE here; inside the per-layer branches below every
    // fetch uses textureSampleGrad (explicit gradients are legal in
    // non-uniform control flow).
    let local = (world.xz - params.chunk.xy) / params.chunk.z;
    let ldx = dpdx(local);
    let ldy = dpdy(local);
    let s = splat_sample(slot, local, ldx, ldy);
    let s2 = splat2_sample(slot, local, ldx, ldy);

    // World-space derivative shared by every layer (uv = world / tile).
    let wdx = dpdx(world.xz);
    let wdy = dpdy(world.xz);

    // Achatamento por distância: perto vê-se o material, longe vê-se cor.
    let view_dist = distance(world, view.world_position.xyz);
    let flat_mix = mix(FLAT_MIN, 1.0, smoothstep(FLAT_NEAR, FLAT_FAR, view_dist));

    var albedo = vec3<f32>(0.0);
    var rough = 0.0;
    var ao = 0.0;

    // Σ dos pesos APÓS o height-bias (renormaliza no fim).
    var wsum = 0.0;
    // ── Frame tangente derivado da normal geométrica (sem atributos de
    // tangente): T = ⊥ à normal no plano horizontal, B fecha a base ortonormal.
    // A projeção top-down (uv = world.xz/tile) torna este frame o espaço
    // tangente correto para os normal maps do pool; em encostas inclina com
    // a superfície, que é o comportamento pretendido.
    let ng = normalize(normal);
    let cross_up = cross(vec3<f32>(0.0, 1.0, 0.0), ng);
    let t_axis = select(vec3<f32>(1.0, 0.0, 0.0), normalize(cross_up), dot(cross_up, cross_up) > 1e-8);
    let b_axis = cross(ng, t_axis);
    // Soma ponderada de normais em espaço-mundo (Σw = 1, cada contribuição
    // ~unitária → normalizar no fim é seguro).
    var n_world = vec3<f32>(0.0);

    if (s.r > WEIGHT_EPSILON) {
        let t = params.tiles[0].x;
        let uv_t = world.xz / t;
        let tex = layer_sample(0, slot, uv_t, wdx / t, wdy / t);
        // Height-bias CONTÍNUO: multiplicador com piso — a layer alta ganha
        // peso na fronteira, a baixa perde um pouco, NINGUÉM colapsa.
        let h = layer_scalar_sample(0, slot, uv_t, wdx / t, wdy / t, true);
        let wb0 = s.r * max(1.0 + HEIGHT_BIAS * (h - 0.5), HEIGHT_BIAS_MIN);
        albedo += wb0 * mix(tex * params.tints[0].rgb, params.flats[0].rgb, flat_mix);
        rough += wb0 * params.roughs[0].x;
        ao += wb0 * layer_scalar_sample(0, slot, uv_t, wdx / t, wdy / t, false);
        wsum += wb0;
        let nm = layer_normal_sample(0, slot, uv_t, wdx / t, wdy / t) * 2.0 - 1.0;
        let k = 1.0 - flat_mix;
        n_world += wb0 * (t_axis * (nm.x * k) + b_axis * (nm.y * k) + ng * (nm.z * k + (1.0 - k)));
    }
    if (s.g > WEIGHT_EPSILON) {
        let t = params.tiles[1].x;
        let uv_t = world.xz / t;
        let tex = layer_sample(1, slot, uv_t, wdx / t, wdy / t);
        // Height-bias CONTÍNUO: multiplicador com piso — a layer alta ganha
        // peso na fronteira, a baixa perde um pouco, NINGUÉM colapsa.
        let h = layer_scalar_sample(1, slot, uv_t, wdx / t, wdy / t, true);
        let wb1 = s.g * max(1.0 + HEIGHT_BIAS * (h - 0.5), HEIGHT_BIAS_MIN);
        albedo += wb1 * mix(tex * params.tints[1].rgb, params.flats[1].rgb, flat_mix);
        rough += wb1 * params.roughs[1].x;
        ao += wb1 * layer_scalar_sample(1, slot, uv_t, wdx / t, wdy / t, false);
        wsum += wb1;
        let nm = layer_normal_sample(1, slot, uv_t, wdx / t, wdy / t) * 2.0 - 1.0;
        let k = 1.0 - flat_mix;
        n_world += wb1 * (t_axis * (nm.x * k) + b_axis * (nm.y * k) + ng * (nm.z * k + (1.0 - k)));
    }
    if (s.b > WEIGHT_EPSILON) {
        let t = params.tiles[2].x;
        let uv_t = world.xz / t;
        let tex = layer_sample(2, slot, uv_t, wdx / t, wdy / t);
        // Height-bias CONTÍNUO: multiplicador com piso — a layer alta ganha
        // peso na fronteira, a baixa perde um pouco, NINGUÉM colapsa.
        let h = layer_scalar_sample(2, slot, uv_t, wdx / t, wdy / t, true);
        let wb2 = s.b * max(1.0 + HEIGHT_BIAS * (h - 0.5), HEIGHT_BIAS_MIN);
        albedo += wb2 * mix(tex * params.tints[2].rgb, params.flats[2].rgb, flat_mix);
        rough += wb2 * params.roughs[2].x;
        ao += wb2 * layer_scalar_sample(2, slot, uv_t, wdx / t, wdy / t, false);
        wsum += wb2;
        let nm = layer_normal_sample(2, slot, uv_t, wdx / t, wdy / t) * 2.0 - 1.0;
        let k = 1.0 - flat_mix;
        n_world += wb2 * (t_axis * (nm.x * k) + b_axis * (nm.y * k) + ng * (nm.z * k + (1.0 - k)));
    }
    if (s.a > WEIGHT_EPSILON) {
        let t = params.tiles[3].x;
        let uv_t = world.xz / t;
        let tex = layer_sample(3, slot, uv_t, wdx / t, wdy / t);
        // Height-bias CONTÍNUO: multiplicador com piso — a layer alta ganha
        // peso na fronteira, a baixa perde um pouco, NINGUÉM colapsa.
        let h = layer_scalar_sample(3, slot, uv_t, wdx / t, wdy / t, true);
        let wb3 = s.a * max(1.0 + HEIGHT_BIAS * (h - 0.5), HEIGHT_BIAS_MIN);
        albedo += wb3 * mix(tex * params.tints[3].rgb, params.flats[3].rgb, flat_mix);
        rough += wb3 * params.roughs[3].x;
        ao += wb3 * layer_scalar_sample(3, slot, uv_t, wdx / t, wdy / t, false);
        wsum += wb3;
        let nm = layer_normal_sample(3, slot, uv_t, wdx / t, wdy / t) * 2.0 - 1.0;
        let k = 1.0 - flat_mix;
        n_world += wb3 * (t_axis * (nm.x * k) + b_axis * (nm.y * k) + ng * (nm.z * k + (1.0 - k)));
    }
    if (s2.r > WEIGHT_EPSILON) {
        let t = params.tiles[4].x;
        let uv_t = world.xz / t;
        let tex = layer_sample(4, slot, uv_t, wdx / t, wdy / t);
        // Height-bias CONTÍNUO: multiplicador com piso — a layer alta ganha
        // peso na fronteira, a baixa perde um pouco, NINGUÉM colapsa.
        let h = layer_scalar_sample(4, slot, uv_t, wdx / t, wdy / t, true);
        let wb4 = s2.r * max(1.0 + HEIGHT_BIAS * (h - 0.5), HEIGHT_BIAS_MIN);
        albedo += wb4 * mix(tex * params.tints[4].rgb, params.flats[4].rgb, flat_mix);
        rough += wb4 * params.roughs[4].x;
        ao += wb4 * layer_scalar_sample(4, slot, uv_t, wdx / t, wdy / t, false);
        wsum += wb4;
        let nm = layer_normal_sample(4, slot, uv_t, wdx / t, wdy / t) * 2.0 - 1.0;
        let k = 1.0 - flat_mix;
        n_world += wb4 * (t_axis * (nm.x * k) + b_axis * (nm.y * k) + ng * (nm.z * k + (1.0 - k)));
    }
    if (s2.g > WEIGHT_EPSILON) {
        let t = params.tiles[5].x;
        let uv_t = world.xz / t;
        let tex = layer_sample(5, slot, uv_t, wdx / t, wdy / t);
        // Height-bias CONTÍNUO: multiplicador com piso — a layer alta ganha
        // peso na fronteira, a baixa perde um pouco, NINGUÉM colapsa.
        let h = layer_scalar_sample(5, slot, uv_t, wdx / t, wdy / t, true);
        let wb5 = s2.g * max(1.0 + HEIGHT_BIAS * (h - 0.5), HEIGHT_BIAS_MIN);
        albedo += wb5 * mix(tex * params.tints[5].rgb, params.flats[5].rgb, flat_mix);
        rough += wb5 * params.roughs[5].x;
        ao += wb5 * layer_scalar_sample(5, slot, uv_t, wdx / t, wdy / t, false);
        wsum += wb5;
        let nm = layer_normal_sample(5, slot, uv_t, wdx / t, wdy / t) * 2.0 - 1.0;
        let k = 1.0 - flat_mix;
        n_world += wb5 * (t_axis * (nm.x * k) + b_axis * (nm.y * k) + ng * (nm.z * k + (1.0 - k)));
    }
    if (s2.b > WEIGHT_EPSILON) {
        let t = params.tiles[6].x;
        let uv_t = world.xz / t;
        let tex = layer_sample(6, slot, uv_t, wdx / t, wdy / t);
        // Height-bias CONTÍNUO: multiplicador com piso — a layer alta ganha
        // peso na fronteira, a baixa perde um pouco, NINGUÉM colapsa.
        let h = layer_scalar_sample(6, slot, uv_t, wdx / t, wdy / t, true);
        let wb6 = s2.b * max(1.0 + HEIGHT_BIAS * (h - 0.5), HEIGHT_BIAS_MIN);
        albedo += wb6 * mix(tex * params.tints[6].rgb, params.flats[6].rgb, flat_mix);
        rough += wb6 * params.roughs[6].x;
        ao += wb6 * layer_scalar_sample(6, slot, uv_t, wdx / t, wdy / t, false);
        wsum += wb6;
        let nm = layer_normal_sample(6, slot, uv_t, wdx / t, wdy / t) * 2.0 - 1.0;
        let k = 1.0 - flat_mix;
        n_world += wb6 * (t_axis * (nm.x * k) + b_axis * (nm.y * k) + ng * (nm.z * k + (1.0 - k)));
    }
    if (s2.a > WEIGHT_EPSILON) {
        let t = params.tiles[7].x;
        let uv_t = world.xz / t;
        let tex = layer_sample(7, slot, uv_t, wdx / t, wdy / t);
        // Height-bias CONTÍNUO: multiplicador com piso — a layer alta ganha
        // peso na fronteira, a baixa perde um pouco, NINGUÉM colapsa.
        let h = layer_scalar_sample(7, slot, uv_t, wdx / t, wdy / t, true);
        let wb7 = s2.a * max(1.0 + HEIGHT_BIAS * (h - 0.5), HEIGHT_BIAS_MIN);
        albedo += wb7 * mix(tex * params.tints[7].rgb, params.flats[7].rgb, flat_mix);
        rough += wb7 * params.roughs[7].x;
        ao += wb7 * layer_scalar_sample(7, slot, uv_t, wdx / t, wdy / t, false);
        wsum += wb7;
        let nm = layer_normal_sample(7, slot, uv_t, wdx / t, wdy / t) * 2.0 - 1.0;
        let k = 1.0 - flat_mix;
        n_world += wb7 * (t_axis * (nm.x * k) + b_axis * (nm.y * k) + ng * (nm.z * k + (1.0 - k)));
    }

    // The CPU bakes the eight weights to sum 1; clamp anyway so a fallback
    // plane must not push the sum past 1.
    let total = max(wsum, 1e-4);
    albedo /= total;
    rough = clamp(rough / total, 0.05, 1.0);
    // AO por texel do pool: soma ponderada pelos MESMOS pesos do albedo
    // (plana = 1.0 quando o mundo não tem `ao.ktx2`).
    albedo *= mix(1.0, ao / total, AO_STRENGTH);
    // O `n_world` acumulou pesos crus (soma ≥ 1 pelo clamp do CPU); a
    // normalização dispensa dividir pelo total antes.
    let n_detail = normalize(n_world);

    // ── Cliff walls: triplanar 2-fetch + estratos ─────────────────────────
    //
    // A projeção top-down do splat estica-se nas paredes ("plastilina").
    // Faces mais íngremes que o cliff-angle (`params.walls_a.x`; ≥ 1 desliga o
    // caminho, const-folded) trocam o blend splat pela ROCK layer do chunk
    // (a mountain_stone quando o chunk a carregou), com bandas de estratos
    // em world.y a fazerem a parede ler como rocha sedimentar.
    var wall_n = vec3<f32>(0.0, 1.0, 0.0);
    var tri_mix = 0.0;
    if (params.walls_a.x < 1.0) {
        // O declive vem da normal INTERPOLADA, não das derivadas de ecrã.
        // `cross(dpdx(world), dpdy(world))` é a normal do TRIÂNGULO: constante
        // dentro dele e descontínua na aresta, por isso o gate saltava de
        // triângulo para triângulo e a encosta enchia-se de manchas de pedra
        // com bordas poligonais retas (o "faixas/manchas nas montanhas"). A
        // normal do vértice vem de `HeightField::sample_normal` com um épsilon
        // constante em todo o terreno: é suave entre triângulos E estável
        // entre LODs, portanto o mesmo pixel não muda de rocha para relva
        // quando o chunk troca de nível.
        let geom_n = normal;
        let slope = 1.0 - abs(geom_n.y);
        // Gate DUPLA: declive × fator de região — o
        // alpha das vertex colors transporta a máscara de cliff FILTRADA
        // (componentes conexos com área/queda/extent mínimos, cozida no
        // mesh builder). Um declive espúrio isolado tem fator 0 e nunca
        // ganha pedra; a borda de região faz blend suave. O canal R
        // transporta o WALL SPACE da máscara (0 = brow, 1 = pé, 0.5
        // neutro): meteorização, AO de contacto e a distribuição de
        // escorrimentos/musgo leem-se dele.
        var region = 1.0;
        var wall = 0.5;
#ifdef VERTEX_COLORS
        region = clamp(in.color.a, 0.0, 1.0);
        wall = clamp(in.color.r, 0.0, 1.0);
#endif
        let tri = smoothstep(params.walls_a.x, params.walls_a.x + params.walls_a.y, slope) * region;
        if (tri > 0.001) {
            let rock = i32(params.chunk.w);
            if (rock >= 0) {
                // Só mistura a normal de parede quando o chunk TEM rock —
                // sem ela o bump ficava (0,1,0) e a parede lia iluminada
                // como chão plano (flat/estourada).
                tri_mix = tri;
                let uv_zy = vec2<f32>(world.z, world.y);
                let uv_xy = vec2<f32>(world.x, world.y);
                let dzy_x = dpdx(uv_zy);
                let dzy_y = dpdy(uv_zy);
                let dxy_x = dpdx(uv_xy);
                let dxy_y = dpdy(uv_xy);
                let use_xy = abs(geom_n.x) < abs(geom_n.z);
                let side = select(uv_zy, uv_xy, use_xy);
                let sd = select(dzy_x, dxy_x, use_xy);
                let sy = select(dzy_y, dxy_y, use_xy);
                let t = params.tiles[rock].x;
                let rock_tex = layer_sample(rock, slot, side / t, sd / t, sy / t);
                // Detail normal do LUMINANCE (fallback sem bindings novas):
                // 2 fetches extra na MESMA textura — o gradiente de
                // luminância é o relevo da rocha. Some ao brilho à
                // distância (flat_mix) para não cintilar longe.
                let luma = vec3<f32>(0.299, 0.587, 0.114);
                let bump = 1.1 * (1.0 - flat_mix);
                if (bump > 0.01) {
                    let e = 0.35 / t;
                    let c0 = dot(rock_tex, luma);
                    let cu = dot(layer_sample(rock, slot, side / t + vec2<f32>(e, 0.0), sd / t, sy / t), luma);
                    let cv = dot(layer_sample(rock, slot, side / t + vec2<f32>(0.0, e), sd / t, sy / t), luma);
                    let u_axis = select(vec3<f32>(0.0, 0.0, 1.0), vec3<f32>(1.0, 0.0, 0.0), use_xy);
                    wall_n = normalize(geom_n
                        - (u_axis * (cu - c0) + vec3<f32>(0.0, 1.0, 0.0) * (cv - c0)) * bump);
                }
                let band = world.y / params.walls_a.z;
                let band_id = floor(band);
                let hue = fract(sin(band_id * vec3<f32>(12.9898, 78.233, 37.719)) * 43758.5453);
                // Estratos cromáticos: cada banda puxa para um tom próprio
                // (quente ↔ frio) e 1 em 4 bandas é um banco DURO — mais
                // claro, o estrato resistente que sai à frente na erosão.
                let warm = vec3<f32>(
                    1.0 - params.walls_a.w,
                    1.0 - params.walls_a.w * 0.75,
                    1.0 - params.walls_a.w * 0.45,
                );
                let cool = vec3<f32>(
                    1.0 + params.walls_a.w * 0.45,
                    1.0 + params.walls_a.w * 0.75,
                    1.0 + params.walls_a.w,
                );
                let band_tint = mix(warm, cool, hue);
                let band_mod = band_id - floor(band_id * 0.25) * 4.0;
                let hard = step(band_mod, 0.5) * 0.14;
                let line = smoothstep(0.82, 1.0, fract(band)) * params.walls_a.w * 0.8;
                // ── Fade dos detalhes SUB-PIXEL ────────────────────────────
                // Estratos (4 m), escorrimentos (~4 m) e o bump de luminância
                // são detalhe de PERTO. A 300 m uma banda de 4 m ocupa ~1 px:
                // o passo `floor(world.y / 4)` deixa de ser rocha sedimentar e
                // vira aliasing — riscas horizontais claras/escuras a
                // atravessar a montanha inteira (o "faixas nas montanhas"). O
                // mesmo `flat_mix` que já achata a textura por distância
                // desliga-os: perto nada muda, longe fica a cor plana da
                // camada. Sem isto nenhum mipmap ajuda — a banda é aritmética
                // no fragmento, não um texel.
                let detail = 1.0 - flat_mix;
                // params.walls_b.x: a parede le PEDRA ESCURA mesmo sob
                // paletas claras — os tints por slot existem para o chao a
                // pleno sol (mountain_stone clareia 1.35x); o rochedo
                // devolve o texel a ~45% (o escuro do basalto da referencia).
                var rock_col = rock_tex * params.tints[rock].rgb * params.walls_b.x
                    * mix(vec3<f32>(1.0), band_tint, detail)
                    * (1.0 - line * detail)
                    * (1.0 + hard * detail);
                // Meteorização vertical (wall space): o brow seca ao sol,
                // o pé ganha poeira de detrito; AO de contacto onde a
                // parede encosta no chão; escorrimentos — faixas verticais
                // de água (noise esticado em Y), mais fortes na metade
                // inferior onde a humidade escorre.
                let weather = mix(1.06, 0.88, wall);
                let toe_ao = 1.0 - 0.38 * smoothstep(0.82, 0.98, wall);
                let su = vec2<f32>((world.x + world.z) * 0.22, world.y * 0.06);
                let streak_n = vnoise(su) * 0.65 + vnoise(su * 2.7) * 0.35;
                let streak = 1.0
                    - params.walls_b.y * detail * smoothstep(0.48, 0.88, streak_n) * mix(0.55, 1.0, wall);
                rock_col = rock_col * weather * toe_ao * streak;
                rock_col = mix(rock_col, params.flats[rock].rgb, flat_mix);
                albedo = mix(albedo, rock_col, tri);
                rough = mix(rough, params.roughs[rock].x, tri);
            }
        }
        // Musgo procedural: manchas húmidas nos OMBROS e flancos médios da
        // região de cliff (declive médio — nem o plano da relva, nem a face
        // nua), mais denso perto do pé onde a humidade se acumula. O gate
        // pela `region` impede musgo em colinas longe de qualquer parede.
        // Também desvanece com a distância: as manchas têm ~6 m e ao longe
        // viravam salpicos verdes de 1 px na encosta.
        let moss_n = vnoise(world.xz * 0.17) * 0.6 + vnoise(world.xz * 0.51) * 0.4;
        let moss_band = smoothstep(0.10, 0.20, slope) * (1.0 - smoothstep(0.50, 0.78, slope));
        let moss = params.walls_b.z * region * moss_band * (1.0 - flat_mix)
            * smoothstep(0.50, 0.78, moss_n)
            * mix(0.55, 1.25, wall);
        albedo = mix(albedo, vec3<f32>(0.17, 0.24, 0.08), clamp(moss, 0.0, 0.85));
    }

    // ── Chuva: chão molhado (r3) ────────────────────────────────────────────
    // `walls_b.w` transporta a chuva (0..1, publisher `terrain_rain_wetness`).
    // Molhar = escurecer o albedo (água absorve) e abrir um gloss de poça no
    // CHÃO plano (a rocha das paredes já é rugosa ao natural); o specular do
    // sol/IBL faz o resto.
    let wet = clamp(params.walls_b.w, 0.0, 1.0) * (1.0 - clamp(tri_mix, 0.0, 1.0) * 0.7);
    if (wet > 0.001) {
        albedo *= mix(1.0, 0.72, wet);
        rough = mix(rough, 0.16, wet);
    }

    // ── Aerial perspective (r2) ────────────────────────────────────────────
    // `day_tint` transporta agora o TINT DO HORIZONTE publicado pela
    // atmosfera (`w = 1` liga): o chão distante mistura-se para a cor do céu
    // ANTES da luz e da fog — as montanhas ao fundo leem-se da cor do ar
    // (azuis de dia, cor de crepúsculo à hora dourada) em vez de cinza
    // estéril. O achatamento FLAT_FAR dá-lhe a cor plana da layer; ISTO dá o
    // degradê atmosférico por cima dela.
    if (params.day_tint.w > 0.5) {
        let aerial = smoothstep(320.0, 1100.0, view_dist) * 0.55;
        albedo = mix(albedo, params.day_tint.rgb, aerial);
    }

    // ── PBR real ──────────────────────────────────────────────────────────
    // Sol direcional com sombras em cascata, luzes pontuais (clustered),
    // ambiente e specular — o mesmo caminho do StandardMaterial alimentado
    // com o nosso albedo/normal de 8 layers + triplanar. O `day_tint` do
    // caminho fake SAIU do albedo: com luz real, a hora do dia já escurece
    // e aquece o chão (sun_drive + daycycle_drive) e o tint compunha-se
    // duas vezes. `sun_dir`/`day_tint` continuam no uniform por compatibilidade
    // de layout (e para o `viber.debug.ground{...}`) mas já não são lidos.
    let n = normalize(mix(n_detail, wall_n, clamp(tri_mix, 0.0, 1.0)));

    var pbr_input = pbr_input_new();
    pbr_input.flags = mesh[in.instance_index].flags;
    pbr_input.is_orthographic = view.clip_from_view[3].w == 1.0;
    pbr_input.V = calculate_view(in.world_position, pbr_input.is_orthographic);
    pbr_input.frag_coord = in.position;
    pbr_input.world_position = in.world_position;
    // A `world_normal` alimenta o normal-offset bias das sombras — normalizada,
    // com o flip de faces (cull off: a barriga dos overhangs é vista por dentro).
    pbr_input.world_normal = normalize(select(-in.world_normal, in.world_normal, is_front));
    pbr_input.N = n;
    // Opaco (alpha mode 0) + receptor de fog da câmara.
    pbr_input.material.flags = STANDARD_MATERIAL_FLAGS_FOG_ENABLED_BIT;
    pbr_input.material.base_color = vec4<f32>(albedo, 1.0);
    pbr_input.material.perceptual_roughness = rough;

    var diffuse_occlusion = vec3<f32>(1.0);
    var specular_occlusion = 1.0;
#ifdef SCREEN_SPACE_AMBIENT_OCCLUSION
    let ssao = textureLoad(screen_space_ambient_occlusion_texture, vec2<i32>(in.position.xy), 0i).r;
    diffuse_occlusion = ssao_multibounce(ssao, albedo);
    // Lagarde and Rousiers 2014, "Moving Frostbite to Physically Based Rendering"
    let ndv = max(dot(n, pbr_input.V), 0.0001);
    let rough_linear = perceptualRoughnessToRoughness(rough);
    specular_occlusion = saturate(pow(ndv + ssao, exp2(-16.0 * rough_linear - 1.0)) - 1.0 + ssao);
#endif
    pbr_input.diffuse_occlusion = diffuse_occlusion;
    pbr_input.specular_occlusion = specular_occlusion;

    var out: FragmentOutput;
    out.color = apply_pbr_lighting(pbr_input);
    // Fog da câmara (`DistanceFog`): aplicada DENTRO do shader do material —
    // sem ela o terreno por layers lia o horizonte a 100% de contraste, as
    // transições de LOD ao longe ficavam duras e o pop-in de chunks era
    // visível. A ordem é a do pipeline: fog antes do tone mapping (nó de
    // pós-processo no 0.19 — TONEMAP_IN_SHADER não está definido aqui).
    out.color = main_pass_post_lighting_processing(pbr_input, out.color);
    return out;
}
