import { defineComponent, F32, U8 } from '../../core/ecs/component-storage';

export const ParticleEmitter = defineComponent({
  active: U8,
  preset: U8,
  emissionRate: F32,
  duration: F32,
  startLifeMin: F32,
  startLifeMax: F32,
  startSpeedMin: F32,
  startSpeedMax: F32,
  startSizeMin: F32,
  startSizeMax: F32,
  startColorR: F32,
  startColorG: F32,
  startColorB: F32,
  startColorA: F32,
  worldSpace: U8,
  renderMode: U8,
  looping: U8,
  burst: U8,
  burstCount: F32,
  shapeRadius: F32,
  shapeAngle: F32,
});
